# Theme configuration
title: Sudoku by C0ZEN
name: Sudoku
short_name: Sudoku
description: Sudoku app to improve my Front-End skills and experiment stuff.
permalink: pretty
url: https://c0zen.github.io/sudoku/
canonical_url: https://c0zen.github.io/sudoku/
color: '#16A085'
version: 0.1.143210

# Url
homePageUrl: https://c0zen.github.io/sudoku/
baseUrl: https://c0zen.github.io/sudoku/
gitHubUrl: https://github.com/C0ZEN/sudoku

# SEO configuration
author: C0ZEN
author_email: geoffrey.testelin@gmail.com
author_url: http://www.geoffreytestelin.com/
twitter:
  username: C0ZEN
logo: /images/logo.png
social:
  name: Geoffrey Testelin
  links:
    - https://twitter.com/C0ZEN
    - https://github.com/C0ZEN
    - https://www.linkedin.com/in/testelingeoffrey/
    - https://codepen.io/C0ZEN/
    - https://github.com/C0ZEN
    - http://www.geoffreytestelin.com/
    - https://stackoverflow.com/users/4440414/c0zen
lang: en
feed:
  path: feed.xml

# Plugins
plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-mentions
